### ISSUE TITLE
Can Not Find Path

### ISSUE THREAD

**Issue by AlixeAtTwitch** [Juraji/Biliomi#1]
![Can Not Find Path](http://alixe.pro/share/img/cmd_140553470b200118.png)

**Comment by Juraji** [comment]
Hey @AlixeAtTwitch, thanks for trying Biliomi.
The windows start script shows that error when it's not able to find your Java installation.
Make sure you've got Java 8 installed which can be found at [this link](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html).
Also make sure you have the latest version of Biliomi, after all the latest version is the best version!

I can't wrap my head around why that website is still so cluttery... Here's a screenshot for ya, Download and install the one outlined in red. Enjoy!
![untitled-1](https://user-images.githubusercontent.com/2438122/35473292-772722e2-037e-11e8-9b0b-553bf24237ba.jpg)

**Comment by AlixeAtTwitch** [comment]
i have been running other java bots like phantom nbot for the past 23 yeasr so this is not the issue also screen shot of the version i have installed

![img here](http://alixe.pro/share/img/cmd_172224652o270118.png)

**Comment by Juraji** [comment]
Nice, that is PhantomBot's start script. I suppose it would just work indeed.
Thanks for trying and finding a solution. I will make a note to edit the windows start script for the next release!

**Comment by Juraji** [comment]
I [released a new version](https://github.com/Juraji/Biliomi/releases/tag/v3.18.1) of Biliomi that fixes this issue. The Windows start script has been completely revised.

I'm closing this issue for now, feel free to open a new issue if you're experiencing any problems.
